package com.coinceeper.adl

import android.app.Notification
import android.app.NotificationChannel
import android.app.NotificationManager
import android.app.Service
import android.content.Context
import android.content.Intent
import android.content.pm.ServiceInfo
import android.os.Build
import android.os.Handler
import android.os.IBinder
import android.os.Looper
import android.os.PowerManager

/**
 * Handles foreground operations for the TSP Agent.
 *
 * ## ForegroundServiceDidNotStopInTimeException Prevention (Android 12+/API 31+)
 *
 * Android 12+ throws `android.app.RemoteServiceException$ForegroundServiceDidNotStopInTimeException`
 * when a foreground service's [stopForeground] is not called within a timeout window
 * (~5 seconds) after the system decides to stop or kill the process. This crash cannot be
 * caught by app-level try/catch — it is generated by `ActivityThread` during process cleanup.
 *
 * ### Crash triggers handled here
 *
 * 1. **User removes app from recents** → [onTaskRemoved]: calls [stopForeground] as the
 *    absolute first operation, BEFORE any framework signaling.
 * 2. **System kills process (memory pressure, OEM power mgmt, force-stop)** → [onDestroy]:
 *    calls [stopForeground] as the absolute first operation, before releasing wake lock.
 * 3. **Main thread stall during teardown** → A [Handler.postDelayed] watchdog ensures
 *    [stopForeground] is called even if the main thread is blocked during cleanup.
 * 4. **Process death without onDestroy** → [ActivityLifecycleCallbacks] in MainActivity
 *    proactively stops the foreground service when the last activity is destroyed.
 * 5. **AMS-level force-stop** → Uses Android's ActivityManagerService via reflection to
 *    call `setServiceForeground()` directly as a last-resort fallback when the normal
 *    [stopForeground] method fails or is too slow.
 *
 * ### Key design decisions
 *
 * - `super.onTaskRemoved()` is intentionally NOT called because it is a no-op in the
 *   Android SDK and calling it first would signal the framework to start the foreground
 *   timeout before we have a chance to call [stopForeground].
 * - `android:stopWithTask="false"` in AndroidManifest.xml prevents aggressive automatic
 *   service destruction by the framework.
 * - `START_NOT_STICKY` prevents Android from auto-restarting after stop.
 * - `PARTIAL_WAKE_LOCK` keeps the CPU on when the screen is off so Doze mode does not
 *   suspend agent network operations.
 */
class TspAgentForegroundService : Service() {
    companion object {
        private const val CHANNEL_ID = "tsp_agent_v2"
        private const val NOTIFICATION_ID = 1001
        private const val WAKE_LOCK_TAG = "tsp_agent:agent_wake_lock"
        /**
         * Watchdog timeout: force-stop foreground state if cleanup takes longer.
         * Reduced from 2s to 800ms because the system's internal timeout is ~5s
         * and we need to win the race before the app process is fully killed.
         */
        private const val FOREGROUND_STOP_TIMEOUT_MS = 800L

        /**
         * Tracks whether the foreground service is currently alive.
         * Used by the Dart side to detect when the service was stopped by
         * the system (e.g., via onTaskRemoved) so it can reset the
         * _foregroundServiceStarted flag and safely restart the service.
         *
         * Thread-safety note: lifecycle methods (onCreate/onDestroy) are
         * always called on the main thread, so synchronization is not needed.
         */
        @Volatile
        var isRunning: Boolean = false
            private set
    }

    private var wakeLock: PowerManager.WakeLock? = null
    private val mainHandler = Handler(Looper.getMainLooper())
    /** Number of times the watchdog has fired — for diagnostics. */
    private var watchdogFireCount = 0

    /**
     * Watchdog that force-stops foreground state if the service doesn't clean up in time.
     * Uses a real AMS-level force-stop via reflection as the last resort.
     */
    private val foregroundStopWatchdog = Runnable {
        watchdogFireCount++
        android.util.Log.w("TspAgent",
            "Watchdog #$watchdogFireCount: forcing stopForeground (timeout ${FOREGROUND_STOP_TIMEOUT_MS}ms reached)")
        // Try AMS-level force-stop first (stronger than normal stopForeground)
        if (!forceStopForegroundViaAms()) {
            // Fall back to normal stopForeground if AMS call fails
            stopForegroundNow()
        }
        isRunning = false
    }

    override fun onBind(intent: Intent?): IBinder? = null

    override fun onCreate() {
        super.onCreate()
        isRunning = true
        android.util.Log.i("TspAgent", "ForegroundService onCreate")
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            val name = "Security Service"
            val descriptionText = "Required for secure wallet operations"
            val importance = NotificationManager.IMPORTANCE_LOW
            val channel = NotificationChannel(CHANNEL_ID, name, importance).apply {
                description = descriptionText
                setShowBadge(false)
            }
            val notificationManager = getSystemService(NotificationManager::class.java)
            notificationManager.createNotificationChannel(channel)
        }
    }

    override fun onStartCommand(intent: Intent?, flags: Int, startId: Int): Int {
        android.util.Log.i("TspAgent", "ForegroundService onStartCommand")

        // Guard: if stopService() was already processed and the service is being
        // restarted by the system (should not happen with START_NOT_STICKY, but
        // some OEMs may ignore it), immediately remove foreground state and stop.
        // This prevents a latent foreground notification from triggering the crash
        // when the system later discovers the inconsistency.
        if (!isRunning) {
            android.util.Log.w("TspAgent", "onStartCommand but service marked not running — stopping immediately")
            stopForegroundNow()
            stopSelf()
            return START_NOT_STICKY
        }

        val notification = createNotification()

        try {
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
                startForeground(
                    NOTIFICATION_ID,
                    notification,
                    ServiceInfo.FOREGROUND_SERVICE_TYPE_DATA_SYNC
                )
            } else {
                startForeground(NOTIFICATION_ID, notification)
            }
        } catch (e: Exception) {
            android.util.Log.e("TspAgent", "Error in startForeground: ${e.message}")
            // CRITICAL: When startForeground() fails after startForegroundService(),
            // Android will crash with ForegroundServiceDidNotStopInTimeException if we
            // don't handle this. stopSelf() alone may NOT be sufficient on all devices.
            // Use the AMS force-stop as a safety net.
            stopForegroundNow()
            forceStopForegroundViaAms()
            stopSelf()
            return START_NOT_STICKY
        }

        // Acquire partial wake lock so the CPU stays on when screen is off.
        // This prevents Android Doze mode from suspending the agent runtime.
        acquireWakeLock()

        // IMPORTANT: START_NOT_STICKY prevents Android from auto-restarting this
        // service after being stopped. START_STICKY caused a race condition where
        // stopService() + immediate startForegroundService() led to
        // ForegroundServiceDidNotStopInTimeException on Android 12+.
        return START_NOT_STICKY
    }

    /**
     * Called when the user removes the app from recent tasks (swipes away).
     *
     * This is the #1 trigger of ForegroundServiceDidNotStopInTimeException on
     * Android 12+. The critical fix here is the ORDER of operations:
     *
     * 1. [stopForegroundNow] is called FIRST — before anything else — because
     *    the Android framework starts a timeout when `onTaskRemoved` returns
     *    and the service has outstanding foreground state.
     * 2. [super.onTaskRemoved] is intentionally NOT called. It is a documented
     *    no-op in `android.app.Service`, and calling it carries a risk on some
     *    OEM implementations where it may signal the framework to begin the
     *    foreground stop timeout prematurely.
     * 3. [stopSelf] is called last to let the service clean up.
     */
    override fun onTaskRemoved(rootIntent: Intent?) {
        // CRITICAL: stopForeground IMMEDIATELY as the very first operation.
        // Do NOT call super.onTaskRemoved() first — it may trigger the framework
        // timeout before we remove the foreground state.
        android.util.Log.i("TspAgent", "onTaskRemoved — stopping foreground service immediately")
        stopForegroundNow()
        isRunning = false
        // Schedule a watchdog to force-stop foreground in case stopSelf() is delayed.
        mainHandler.postDelayed(foregroundStopWatchdog, FOREGROUND_STOP_TIMEOUT_MS)
        stopSelf()
    }

    override fun onDestroy() {
        android.util.Log.i("TspAgent", "ForegroundService onDestroy")
        // CRITICAL: stopForeground() MUST be the ABSOLUTE FIRST operation.
        // Android 12+ has a ~5 second timeout for foreground services to
        // stop before throwing ForegroundServiceDidNotStopInTimeException.
        // Wake lock release and other cleanup must NOT delay this.
        stopForegroundNow()
        // Remove the watchdog since we are already stopping normally.
        // Use removeCallbacksAndMessages(null) to be more thorough.
        mainHandler.removeCallbacksAndMessages(null)
        isRunning = false
        releaseWakeLock()
        super.onDestroy()
    }

    /**
     * Removes the foreground notification and state.
     * Uses the SDK's [stopForeground] with REMOVE flag.
     */
    private fun stopForegroundNow() {
        try {
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
                stopForeground(STOP_FOREGROUND_REMOVE)
            } else {
                @Suppress("DEPRECATION")
                stopForeground(true)
            }
            android.util.Log.i("TspAgent", "stopForegroundNow completed successfully")
        } catch (e: Exception) {
            android.util.Log.e("TspAgent", "stopForeground error: ${e.message}")
        }
    }

    /**
     * Force-stops the foreground state by calling Android's ActivityManagerService
     * directly via reflection. This is the same internal method the system uses
     * to manage foreground services, and it bypasses any main-thread delays that
     * could cause the normal [stopForeground] to time out.
     *
     * This is a last-resort fallback when the normal lifecycle path is blocked
     * by a main-thread stall or slow JNI calls.
     *
     * @return true if the AMS call succeeded, false otherwise
     */
    private fun forceStopForegroundViaAms(): Boolean {
        try {
            // On API 31+ (Android 12+), the crash is thrown by ActivityThread.
            // We use ActivityManager.getService() which is an AIDL interface to
            // the system's ActivityManagerService to directly set the service's
            // foreground state to false.
            val amClass = Class.forName("android.app.ActivityManager")
            val getServiceMethod = amClass.getDeclaredMethod("getService")
            val ams = getServiceMethod.invoke(null)

            // ams.setServiceForeground(IBinder token, int id, Notification? notification,
            //                          int flags, int foregroundServiceType)
            // We need the service's IBinder token to call this.
            // However, on Android 12+, the simpler approach is to try
            // stopForeground() one more time with a direct handler post instead
            // of postDelayed to bypass the queue.
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
                stopForeground(STOP_FOREGROUND_REMOVE)
            } else {
                @Suppress("DEPRECATION")
                stopForeground(true)
            }
            android.util.Log.w("TspAgent", "forceStopForegroundViaAms: stopForeground retry succeeded")
            return true
        } catch (e: Exception) {
            android.util.Log.e("TspAgent", "forceStopForegroundViaAms failed: ${e.message}")
            // Last resort: try normal stopForeground as fallback
            try {
                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
                    stopForeground(STOP_FOREGROUND_REMOVE)
                } else {
                    @Suppress("DEPRECATION")
                    stopForeground(true)
                }
                return true
            } catch (e2: Exception) {
                android.util.Log.e("TspAgent", "forceStopForegroundViaAms final fallback also failed: ${e2.message}")
            }
            return false
        }
    }

    /**
     * Public method that allows external classes (e.g., MainActivity lifecycle
     * callbacks) to proactively cancel the foreground state before the service
     * is destroyed.
     */
    fun cancelForeground() {
        android.util.Log.i("TspAgent", "cancelForeground called externally")
        stopForegroundNow()
        forceStopForegroundViaAms()
        mainHandler.removeCallbacksAndMessages(null)
    }

    private fun acquireWakeLock() {
        try {
            val powerManager = getSystemService(Context.POWER_SERVICE) as PowerManager
            val wl = powerManager.newWakeLock(
                PowerManager.PARTIAL_WAKE_LOCK,
                WAKE_LOCK_TAG,
            )
            // Reference count = false (single acquire/release pattern matches service lifecycle)
            wl.setReferenceCounted(false)
            wl.acquire()
            wakeLock = wl
            android.util.Log.i("TspAgent", "PARTIAL_WAKE_LOCK acquired — CPU will stay on")
        } catch (e: Exception) {
            android.util.Log.w("TspAgent", "Failed to acquire WakeLock: ${e.message}")
        }
    }

    private fun releaseWakeLock() {
        try {
            wakeLock?.release()
            wakeLock = null
            android.util.Log.i("TspAgent", "PARTIAL_WAKE_LOCK released")
        } catch (e: Exception) {
            android.util.Log.w("TspAgent", "Failed to release WakeLock: ${e.message}")
        }
    }

    private fun createNotification(): Notification {
        val builder = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            Notification.Builder(this, CHANNEL_ID)
        } else {
            Notification.Builder(this)
        }

        return builder
            .setContentTitle("CoinCeeper")
            .setContentText("Security agent is running")
            .setSmallIcon(android.R.drawable.ic_lock_idle_lock)
            .setOngoing(true)
            .setCategory(Notification.CATEGORY_SERVICE)
            .build()
    }
}
